#### NumPy

* NumPy is a Python library.
* It is used for working with arrays.
* It is short for "Numerical Python".
* It is used for computation and processing of single and multi dimensional array of elements.
* Smaller memory consumption and better runtime behavior.

In [ ]:
# To install the library

%pip install numpy

import numpy

##### Basic Operations

In [4]:
import numpy as np

![Numpy Meme](../assets/images/numpy-meme.png)

In [5]:
a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


In [6]:
type(a)

numpy.ndarray

In [7]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)

[1. 2. 3. 4. 5.]


In [9]:
type(a)

numpy.ndarray

In [8]:
a = np.array([1, 2, 3, 4, 5], dtype=str)

print(a)

['1' '2' '3' '4' '5']


In [11]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Get Diamension of a numpy array
a.ndim

1

In [14]:
b.ndim

2

In [15]:
c.ndim

2

In [21]:
d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]
    ]
])

print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [22]:
d.ndim

3

In [23]:
len(d)

2

In [33]:
e = np.array([
    [
        [
            [1, 2],
            [3, 4],
            [5, 6],
            [7, 8]
        ],

        [
            [10, 20],
            [30, 40],
            [50, 60],
            [70, 80]
        ],

        [
            [100, 200],
            [300, 400],
            [500, 600],
            [700, 800]
        ]
    ]
])

print(e)

[[[[  1   2]
   [  3   4]
   [  5   6]
   [  7   8]]

  [[ 10  20]
   [ 30  40]
   [ 50  60]
   [ 70  80]]

  [[100 200]
   [300 400]
   [500 600]
   [700 800]]]]


In [34]:
e.ndim

4

In [35]:
len(e)

1

##### Why Use NumPy?

* In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
* Arrays are very frequently used in data science, where speed and resources are very important.

![numpy arrays diamensions](../assets/images/numpy-arrays_diamensions.png)

![numpy time taken for the loop](../assets/images/numpy-time_taken_for_the_loop.png)

In [37]:
# Get a shape of numpy array

a = np.array([1, 2, 3, 4, 5])

a.shape

(5,)

In [38]:
b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

b.shape

(2, 4)

In [39]:
c = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],

    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]
    ]
])

c.shape

(2, 3, 3)

In [52]:
d = np.array([
    [
        [
            [1, 2],
            [3, 4],
            [5, 6],
            [7, 8]
        ],

        [
            [10, 20],
            [30, 40],
            [50, 60],
            [70, 80]
        ],

        [
            [100, 200],
            [300, 400],
            [500, 600],
            [700, 800]
        ]
    ]
])

d.shape

(1, 3, 4, 2)

In [41]:
d.size

24

In [53]:
d.ndim

4

In [42]:
d.dtype

dtype('int64')

In [44]:
e = np.array([1, 2, 3, 4], dtype=float)

print(e)

[1. 2. 3. 4.]


In [45]:
e.dtype

dtype('float64')

In [46]:
f = np.array([1.2, 3.45, 6.98, 8.99])

print(f)

[1.2  3.45 6.98 8.99]


In [48]:
f.dtype

dtype('float64')

##### Accessing/Changing specific elements, rows & columns etc.

In [61]:
a = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [8, 9, 10, 11, 12, 13, 15]
])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 15]]


In [62]:
a.ndim

2

In [63]:
# Get a specific element [r,c]

print(a[0][3])

4


In [64]:
print(a[0, 3])

4


In [66]:
print(a[1, 0])

8


In [68]:
print(a[1][5])

13


In [24]:
# Get a specific row from a numpy array

print(a[0,:])

[1 2 3 4 5 6]


In [73]:
# Get a specific column from a numpy array

print(a[:,4])

[ 5 12]


In [77]:
print(a[:][:,0])

[1 8]


In [79]:
a = np.array([
    [ 1,  2,  3,  4,  5,  6,  7],
    [ 8,  9, 10, 11, 12, 13, 14]
])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [80]:
a[0, 3] = 40

print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [81]:
a[0][5] = 60

print(a)

[[ 1  2  3 40  5 60  7]
 [ 8  9 10 11 12 13 14]]


In [82]:
# Change the 5th column in 1st row to 50

a[0, 4] = 50

a

array([[ 1,  2,  3, 40, 50, 60,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

##### Zeros/Ones method in NumPy

In [95]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [97]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
print(np.ones((2,3), dtype="int32"))

[[1 1 1]
 [1 1 1]]


In [102]:
print(np.full((3,3), 50, dtype="float64"))

[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]


In [103]:
print(np.full((4, 3), 8, dtype=int))

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [120]:
print(np.random.rand(3, 3))

[[0.00265448 0.47745764 0.99721404]
 [0.90738807 0.74748593 0.77071273]
 [0.96529349 0.14053051 0.03254129]]


In [121]:
print(np.random.random((3, 3)))

[[0.16064248 0.95667393 0.1313758 ]
 [0.14525953 0.43868775 0.52927767]
 [0.66880399 0.76237029 0.32164294]]


In [ ]:
"""
The function np.random.default_rng() 
makes things better than both legacy functions (rand and random) due to three major improvements: 
speed, statistical quality, and independent state management.
"""
np.random.default_rng().random((3,3))

array([[0.70618345, 0.22026779, 0.83786128],
       [0.35979889, 0.27627226, 0.3781278 ],
       [0.66012386, 0.86369442, 0.26745387]])

In [132]:
print(np.random.default_rng(seed=42).random((3,3)), "\n")

print(np.random.default_rng(seed=42).random((3,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]] 

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


In [140]:
print(np.random.randint(-2, 10, (3, 3)))

[[ 8  0  7]
 [ 8  7  7]
 [ 2 -2  2]]


In [ ]:
print(np.random.default_rng().integers(5, 20, (3,3)))

[[ 7 12  8]
 [12  7 19]
 [14 19 11]]


In [154]:
print(np.random.default_rng().uniform(4, 5, (3,3)))

[[4.34750998 4.0305039  4.36481681]
 [4.1913554  4.45585935 4.91328794]
 [4.77677306 4.5600487  4.65080492]]


In [157]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [159]:
print(np.identity(3, dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Practice Questions

##### Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [1]:
2,3,4,5,6
20,30,40,50,60
12,12,12,12,12

(12, 12, 12, 12, 12)

In [10]:
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5, 6], 
    [10, 20, 30, 40, 50, 60], 
    [12, 12, 12, 12, 12, 12],
    [11, 21, 31, 41, 51, 61],    
    [13, 24, 34, 44, 54, 64]
])

print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [12 12 12 12 12 12]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [12]:
a.ndim

2

In [22]:
print(a[:3, 1:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


In [25]:
print(a[0:3, -5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


##### Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

[1 1 1]

[0 1 0]]

Input 2:

5


Output 1:

[[0 0 1 0 0]

[0 0 1 0 0]

[1 1 1 1 1]

[0 0 1 0 0]

[0 0 1 0 0]]

In [41]:
n = int(input("Enter the array size: "))

# Creating an (nxn) array with all zero
arr_1 = np.zeros((n,n), dtype=int)


# Make the middle row and colum all 1's
arr_1[n // 2, :] = 1  # for row change 
arr_1[:, n // 2] = 1  # for column change

print(arr_1)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


Just to help you understand about n//2

In [43]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [12 12 12 12 12 12]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [46]:
a[a.shape[0] // 2, :] = a[:, a.shape[-1] // 2] = 1

print(a)

[[ 1  2  3  1  5  6]
 [10 20 30  1 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31  1 51 61]
 [13 24 34  1 54 64]]


In [48]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

a[a.shape[0] // 2, :] = 1

print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [49]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

a[:, a.shape[1] // 2] = 1 

print(a)

[[ 1  2  3  1  5  6]
 [10 20 30  1 50 60]
 [12 12 12  1 12 12]
 [11 21 31  1 51 61]
 [13 24 34  1 54 64]]


#### Arithmetic Operations with NumPy - Maths + Stats

In [51]:
arr = np.array([range(1, 6)])

arr

array([[1, 2, 3, 4, 5]])

In [52]:
arr + 2

array([[3, 4, 5, 6, 7]])

In [54]:
# DO it for -, /, *, //, ** - ALmost all the operations are satisfied

arr ** 3

array([[  1,   8,  27,  64, 125]])

In [57]:
arr

array([[1, 2, 3, 4, 5]])

In [60]:
print(arr.min())

1


In [61]:
print(np.min(arr))

1


In [63]:
print(arr.max())

5


In [64]:
print(np.max(arr))

5


In [66]:
print(arr.mean(dtype=int))

3


In [67]:
print(np.mean(arr))

3.0


In [68]:
a = np.array([[1,2,3,4], [5,6,7,8]])

print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
print(a.sum())

36


In [70]:
print(np.sum(a))

36


In [71]:
print(a.mean())

4.5


In [74]:
print(np.max(a, axis=0))

[5 6 7 8]


In [75]:
print(np.max(a, axis=1))

[4 8]


In [76]:
print(np.min(a, axis=0))

[1 2 3 4]


In [77]:
print(np.min(a, axis=1))

[1 5]


In [78]:
print(np.sum(a, axis=0))

[ 6  8 10 12]


In [79]:
print(np.sum(a, axis=1))

[10 26]
